updates shell script for better symlink support

diff --git a/link-to-home b/link-to-home
--- a/link-to-home
+++ b/link-to-home
@@ -4,15 +4,22 @@ DIR="$( cd "$( dirname "$0" )" && pwd )"
 
 if [ ! -e $DIR/$1 ]
 then
-    echo "$DIR/$1 not found!"
+    echo "Can't link $DIR/$1 to your home directory because it doesn't exist."
     exit 1
+fi
+
+if [ -L $HOME/$1 ]
+then
+    echo "$HOME/$1 exists and is a symbolic link."
+    echo "Run \`mv $HOME/$1 $HOME/$1.bak\`"
+    exit 2
 fi
 
 echo "creating symlink"
 if (( $(ln -s $DIR/$1 $HOME/$1) ))
 then
     echo "Creating symlink failed."
-    echo "If $HOME/$1 exists, run \`mv $HOME/$1.bak && rm $HOME/$1\`"
+    exit 3
 fi
 
 echo "Symlink created:"
